### ISSUE TITLE
Example in README: Unhandled exception

### ISSUE THREAD

**Issue by janders** [diegomvh/ODataApiGen#5]
When I run the example I see the following unhandled exception:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at ODataApiGen.Models.NavigationPropertyBinding.get_NavigationProperty() in /home/diego/Workspace/GitHub/diegomvh/ODataApiGen/Models/NavigationPropertyBinding.cs:line 43
   at ODataApiGen.Angular.ServiceEntity.<>c.<get_ImportTypes>b__6_6(NavigationPropertyBinding b) in /home/diego/Workspace/GitHub/diegomvh/ODataApiGen/Angular/ServiceEntity.cs:line 37
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at ODataApiGen.Angular.ServiceEntity.get_ImportTypes() in /home/diego/Workspace/GitHub/diegomvh/ODataApiGen/Angular/ServiceEntity.cs:line 37
   at ODataApiGen.Angular.Package.ResolveDependencies() in /home/diego/Workspace/GitHub/diegomvh/ODataApiGen/Angular/Package.cs:line 87
   at ODataApiGen.Program.Main(String[] args) in /home/diego/Workspace/GitHub/diegomvh/ODataApiGen/Program.cs:line 60
```

I'm running docker on a Mac and the example command I'm running is:

```
docker run -it --rm -v ${PWD}:/local diegomvh/odataapigen Name=MsGraph Metadata=https://graph.microsoft.com/v1.0/\$metadata Output=/local
```

However, if I save the xml file locally as trippin.xml the following works:

```
docker run -it --rm -v ${PWD}:/local diegomvh/odataapigen Name=TripPin StringAsEnum=true MetadataFile=/local/trippin.xml Output=/local
```

Thanks,
-JA

**Comment by diegomvh** [comment]
Hi JA,
The problem is in an incomplete reading of the `MsGraph` schema.
From what I see it is necessary to work on the alias of the schema.

```xml
<Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="microsoft.graph" Alias="graph">
```

Thank you very much!

**Comment by janders** [comment]
Hi Diego,

It works for me now on my Mac, but not Windows 10. Honestly, I'm not sure
if I have Windows 10 configured properly.

I saw an issue where a user asked for a request to load an xml file.  I
tried this but it doesn't work (guess it has to do with the schema since it
tries to use TripPin):

docker run -it --rm -v ${PWD}:/local diegomvh/odataapigen Name=test
StringAsEnum=true MetadataFile=/local/test-metadata.xml Output=/local

Thanks for your work!

- JA

**Comment by diegomvh** [comment]
Create an example that uses a local file to generate the schema.
[MsGraph](https://github.com/diegomvh/ODataApiGen/blob/master/Examples/MsGraph/msgraph.sh)

`StringAsEnum` is no longer a parameter for the generator. Remove some parameters that are from angular-odata configuration

regards

**Comment by janders** [comment]
Works great, thank you!
- JA
